# Generated by Django 5.0.6 on 2024-08-31 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ja",
            name="userconfirmation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.suporter",
            ),
        ),
    ]
